<?php

namespace SymfonyDev\TCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentInfoRepository extends EntityRepository
{
}
